'use client'

/**
 * RegisterSW — registers /sw.js (generated by next-pwa) once on mount.
 *
 * next-pwa v5 auto-injected the registration via pages/_document.js.
 * App Router has no _document.js, so the SW must be registered manually.
 * This component renders nothing and runs the registration exactly once.
 */

import { useEffect } from 'react'
import { logger } from '@/lib/logger'

export function RegisterSW() {
  useEffect(() => {
    if (!('serviceWorker' in navigator)) return

    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then(() => {
        logger.info('RegisterSW', 'SW registered successfully')
      })
      .catch((err: unknown) => {
        logger.error('RegisterSW', 'SW registration failed', err)
      })
  }, [])

  return null
}
