/**
 * seed-intent-embeddings.ts — Precompute intent embeddings for the SemanticRouter.
 *
 * Reads INTENT_DEFINITIONS from lib/ai/router/intents.ts, calls the
 * Supabase.ai `gte-small` embed function for every example phrase, and
 * writes the result to TWO files (Node + Deno mirror):
 *
 *   - lib/ai/router/intent-embeddings.generated.json
 *   - supabase/functions/_shared/router/intent-embeddings.generated.json
 *
 * Run after editing intents.ts. Idempotent.
 *
 *   npx tsx scripts/seed-intent-embeddings.ts
 *
 * Required env (read from .env.local):
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */

import * as dotenv from 'dotenv'
import { writeFileSync } from 'node:fs'
import { resolve }       from 'node:path'

import { INTENT_DEFINITIONS } from '../lib/ai/router/intents'
import { SupabaseEdgeEmbedder } from '../lib/ai/memory/Embedder'
import type { IntentPrototype } from '../lib/ai/router/contracts'

dotenv.config({ path: '.env.local' })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('❌ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const OUT_FILES = [
  resolve(__dirname, '..', 'lib/ai/router/intent-embeddings.generated.json'),
  resolve(__dirname, '..', 'supabase/functions/_shared/router/intent-embeddings.generated.json'),
]

async function main(): Promise<void> {
  const embedder = new SupabaseEdgeEmbedder(`${SUPABASE_URL}/functions/v1/embed-text`, SERVICE_KEY!)
  const prototypes: IntentPrototype[] = []

  let total = 0
  for (const def of INTENT_DEFINITIONS) total += def.examples.length

  console.log(`🚀 Embedding ${total} phrases across ${INTENT_DEFINITIONS.length} intents…`)

  let done = 0
  for (const def of INTENT_DEFINITIONS) {
    for (const ex of def.examples) {
      const res = await embedder.embed(ex.text)
      done++
      if (!res.ok) {
        console.error(`❌ [${done}/${total}] failed "${ex.text}": ${res.error}`)
        process.exit(1)
      }
      prototypes.push({ intent: def.name, text: ex.text, embedding: res.value })
      console.log(`✓  [${done}/${total}] ${def.name}: "${ex.text}"`)
    }
  }

  const payload = {
    _:          'Auto-generated by scripts/seed-intent-embeddings.ts — do not edit by hand.',
    dimensions: 384,
    generated:  new Date().toISOString(),
    prototypes,
  }

  const json = JSON.stringify(payload, null, 2) + '\n'
  for (const path of OUT_FILES) {
    writeFileSync(path, json, 'utf8')
    console.log(`📝 wrote ${path}`)
  }

  console.log(`✅ Done — ${prototypes.length} prototypes written.`)
}

main().catch((err) => {
  console.error('💥 Unhandled error:', err)
  process.exit(1)
})
